spring.application.name=my-greetings-app
server.port=8080

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:greetingsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=alpha
spring.datasource.password=alpha#123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console